FROM golang:1.24-alpine

RUN apk add --no-cache curl git
RUN adduser -D -u 1000 appuser

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin
USER appuser

COPY . .
CMD ["air"]
