basePath: /api
host: localhost:8080
info:
  contact: {}
  description: API que provee el backend necesario para la empresa DAPA.
  title: De aquí para allá API
  version: "0.1"
paths: {}
swagger: "2.0"
